# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShogunTonight' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
     pod 'RSKImageCropper'
     pod 'QBImagePickerController'

  # Pods for ShogunTonight

  target 'ShogunTonight-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShogunTonightTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ShogunTonight-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShogunTonight-tvOS

end
